blocks = [
    {"block": "cut_netherite", "parent": "Blocks.NETHERITE"},
    {"block": "dripstone_brick_pillar", "parent": "Blocks.DRIPSTONE_BLOCK"},
    {"block": "cut_netherite_stairs", "parent": "Blocks.NETHERITE"},
    {"block": "diorite_brick_wall", "parent": "Blocks.DIORITE"},
    {"block": "chiseled_diorite_bricks", "parent": "Blocks.DIORITE"},
    {"block": "cracked_basalt_bricks", "parent": "Blocks.BASALT"},
    {"block": "diorite_brick_stairs", "parent": "Blocks.DIORITE"},
    {"block": "cut_iron_stairs", "parent": "Blocks.IRON_BLOCK"},
    {"block": "obsidian_brick_slab", "parent": "Blocks.OBSIDIAN"},
    {"block": "cut_coal_stairs", "parent": "Blocks.COAL_BLOCK"},
    {"block": "tuff_brick_wall", "parent": "Blocks.TUFF"},
    {"block": "granite_brick_wall", "parent": "Blocks.GRANITE"},
    {"block": "chiseled_obsidian_bricks", "parent": "Blocks.OBSIDIAN"},
    {"block": "cut_gold_slab", "parent": "Blocks.GOLD_BLOCK"},
    {"block": "granite_brick_stairs", "parent": "Blocks.GRANITE"},
    {"block": "dripstone_brick_wall", "parent": "Blocks.DRIPSTONE_BLOCK"},
    {"block": "nether_brick_pillar", "parent": "Blocks.NETHER_BRICKS"},
    {"block": "amethyst_brick_slab", "parent": "Blocks.AMETHYST_BLOCK"},
    {"block": "basalt_brick_slab", "parent": "Blocks.BASALT"},
    {"block": "basalt_brick_stairs", "parent": "Blocks.BASALT"},
    {"block": "chiseled_tuff_bricks", "parent": "Blocks.TUFF"},
    {"block": "cracked_purpur", "parent": "Blocks.PURPUR_BLOCK"},
    {"block": "andesite_brick_stairs", "parent": "Blocks.AMETHYST_BLOCK"},
    {"block": "cracked_dripstone_bricks", "parent": "Blocks.DRIPSTONE_BLOCK"},
    {"block": "chiseled_andesite_bricks", "parent": "Blocks.ANDESITE"},
    {"block": "cracked_red_nether_bricks", "parent": "Blocks.RED_NETHER_BRICKS"},
    {"block": "cut_iron", "parent": "Blocks.IRON_BLOCK"},
    {"block": "chiseled_basalt_bricks", "parent": "Blocks.BASALT"},
    {"block": "calcite_brick_stairs", "parent": "Blocks.CALCITE"},
    {"block": "andesite_brick_wall", "parent": "Blocks.AMETHYST_BLOCK"},
    {"block": "tuff_brick_pillar", "parent": "Blocks.TUFF"},
    {"block": "obsidian_brick_stairs", "parent": "Blocks.OBSIDIAN"},
    {"block": "cut_redstone", "parent": "Blocks.REDSTONE_BLOCK"},
    {"block": "amethyst_brick_stairs", "parent": "Blocks.AMETHYST_BLOCK"},
    {"block": "obsidian_brick_pillar", "parent": "Blocks.OBSIDIAN"},
    {"block": "cracked_diorite_bricks", "parent": "Blocks.DIORITE"},
    {"block": "chiseled_purpur", "parent": "Blocks.PURPUR_BLOCK"},
    {"block": "cut_netherite_slab", "parent": "Blocks.NETHERITE"},
    {"block": "cracked_amethyst_bricks", "parent": "Blocks.AMETHYST_BLOCK"},
    {"block": "calcite_brick_wall", "parent": "Blocks.CALCITE"},
    {"block": "prismarine_pillar", "parent": "Blocks.PRISMARINE"},
    {"block": "andesite_bricks", "parent": "Blocks.ANDESITE"},
    {"block": "cracked_end_stone_bricks", "parent": "Blocks.END_STONE"},
    {"block": "granite_brick_slab", "parent": "Blocks.GRANITE"},
    {"block": "cracked_obsidian_bricks", "parent": "Blocks.OBSIDIAN"},
    {"block": "amethyst_brick_pillar", "parent": "Blocks.AMETHYST_BLOCK"},
    {"block": "tuff_bricks", "parent": "Blocks.TUFF"},
    {"block": "chiseled_calcite_bricks", "parent": "Blocks.CALCITE"},
    {"block": "basalt_brick_pillar", "parent": "Blocks.BASALT"},
    {"block": "chiseled_red_nether_bricks", "parent": "Blocks.RED_NETHER_BRICKS"},
    {"block": "cracked_granite_bricks", "parent": "Blocks.GRANITE"},
    {"block": "cracked_prismarine_bricks", "parent": "Blocks.PRISMARINE"},
    {"block": "dripstone_brick_stairs", "parent": "Blocks.DRIPSTONE_BLOCK"},
    {"block": "stone_brick_pillar", "parent": "Blocks.STONE"},
    {"block": "cut_diamond", "parent": "Blocks.DIAMOND_BLOCK"},
    {"block": "cracked_andesite_bricks", "parent": "Blocks.ANDESITE"},
    {"block": "obsidian_bricks", "parent": "Blocks.OBSIDIAN"},
    {"block": "obsidian_brick_wall", "parent": "Blocks.OBSIDIAN"},
    {"block": "granite_brick_pillar", "parent": "Blocks.GRANITE"},
    {"block": "chiseled_end_stone_bricks", "parent": "Blocks.END_STONE"},
    {"block": "cracked_calcite_bricks", "parent": "Blocks.CALCITE"},
    {"block": "amethyst_bricks", "parent": "Blocks.AMETHYST_BLOCK"},
    {"block": "calcite_bricks", "parent": "Blocks.CALCITE"},
    {"block": "cut_lapis_slab", "parent": "Blocks.LAPIS_BLOCK"},
    {"block": "diorite_brick_slab", "parent": "Blocks.DIORITE"},
    {"block": "cut_iron_slab", "parent": "Blocks.IRON_BLOCK"},
    {"block": "chiseled_dripstone_bricks", "parent": "Blocks.DRIPSTONE_BLOCK"},
    {"block": "granite_bricks", "parent": "Blocks.GRANITE"},
    {"block": "diorite_brick_pillar", "parent": "Blocks.DIORITE"},
    {"block": "cut_coal_slab", "parent": "Blocks.COAL_BLOCK"},
    {"block": "cut_emerald_stairs", "parent": "Blocks.EMERALD_BLOCK"},
    {"block": "tuff_brick_slab", "parent": "Blocks.TUFF"},
    {"block": "dripstone_brick_slab", "parent": "Blocks.DRIPSTONE_BLOCK"},
    {"block": "amethyst_brick_wall", "parent": "Blocks.AMETHYST_BLOCK"},
    {"block": "dripstone_bricks", "parent": "Blocks.DRIPSTONE_BLOCK"},
    {"block": "cut_gold_stairs", "parent": "Blocks.GOLD_BLOCK"},
    {"block": "basalt_brick_wall", "parent": "Blocks.BASALT"},
    {"block": "chiseled_prismarine_bricks", "parent": "Blocks.PRISMARINE"},
    {"block": "cut_diamond_slab", "parent": "Blocks.DIAMOND_BLOCK"},
    {"block": "cut_emerald", "parent": "Blocks.EMERALD_BLOCK"},
    {"block": "chiseled_amethyst_bricks", "parent": "Blocks.AMETHYST_BLOCK"},
    {"block": "cut_emerald_slab", "parent": "Blocks.EMERALD_BLOCK"},
    {"block": "end_stone_pillar", "parent": "Blocks.END_STONE"},
    {"block": "chiseled_granite_bricks", "parent": "Blocks.GRANITE"},
    {"block": "calcite_brick_slab", "parent": "Blocks.CALCITE"},
    {"block": "basalt_bricks", "parent": "Blocks.BASALT"},
    {"block": "calcite_brick_pillar", "parent": "Blocks.CALCITE"},
    {"block": "andesite_brick_slab", "parent": "Blocks.ANDESITE"},
    {"block": "red_nether_brick_pillar", "parent": "Blocks.RED_NETHER_BRICKS"},
    {"block": "cut_redstone_slab", "parent": "Blocks.REDSTONE_BLOCK"},
    {"block": "cut_gold", "parent": "Blocks.GOLD_BLOCK"},
    {"block": "andesite_brick_pillar", "parent": "Blocks.ANDESITE"},
    {"block": "cut_lapis_stairs", "parent": "Blocks.LAPIS_BLOCK"},
    {"block": "tuff_brick_stairs", "parent": "Blocks.TUFF"},
    {"block": "cracked_tuff_bricks", "parent": "Blocks.TUFF"},
    {"block": "cut_redstone_stairs", "parent": "Blocks.REDSTONE_BLOCK"},
    {"block": "diorite_bricks", "parent": "Blocks.DIORITE"},
    {"block": "cut_coal", "parent": "Blocks.COAL_BLOCK"},
    {"block": "red_nether_brick_fence", "parent": "Blocks.RED_NETHER_BRICKS"},
    {"block": "cut_diamond_stairs", "parent": "Blocks.DIAMOND_BLOCK"},
    {"block": "cut_lapis", "parent": "Blocks.LAPIS_BLOCK"}
]

template = """
Registry.register(Registries.BLOCK, {block_name}_id, {block_name});
Registry.register(Registries.ITEM, {block_name}_id, new BlockItem({block_name}, new Item.Settings().registryKey(RegistryKey.of(RegistryKeys.ITEM, {block_name}_id))));

"""

mod_id = "blockexpansion"  # Mod ID

# Generación de código
for block in blocks:
    print(template.format(
        block_name=block['block'],
        block_registry=block['parent'],
        mod_id=mod_id
    ))
